name: Update GitHub Activity

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Activity Log
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main # <--- ESTO OBLIGA AL BOT A LEER TU RAMA MAIN

      - name: Deploy GitHub Activity README
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_LINES: 5
