name: Update GitHub Activity

on:
  schedule:
    # Se ejecuta automáticamente cada hora
    - cron: '0 * * * *'
  workflow_dispatch: # Permite que lo arranques tú manualmente

jobs:
  update-readme:
    name: Update Activity Log
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy GitHub Activity README
        uses: gautamkrishnar/user-activity-readme@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Vincula directamente tus etiquetas pegadas en una sola línea
          ACTIVITY_START_TAG: ""
          ACTIVITY_END_TAG: ""
          MAX_LINES: 5
