name: Update GitHub Activity

on:
  schedule:
    # Se ejecuta cada hora de forma automática
    - cron: '0 * * * *'
  workflow_dispatch: # Te permite ejecutarlo manualmente desde la pestaña Actions

jobs:
  update-readme:
    name: Update Activity Log
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy GitHub Activity README
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_LINES: 5
          BRANCH: "main" # <--- ESTA ES LA LÍNEA QUE SOLUCIONA EL ERROR
